# -*- coding: utf-8 -*-
"""OPEN Stock Linear Regression Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z18dmB08c0XMMHebaxfloO8zdnTc6i9L

# Install Packages
"""

pip install yfinance

import pandas as pd

import yfinance as yf

pip install pandas-ta

import pandas_ta as ta

"""#Stock History"""

OPEN_stock = yf.Ticker("OPEN")
print(OPEN_stock)
OPEN_stock_history = OPEN_stock.history(start="2025-07-01", end="2025-12-18")
print(OPEN_stock_history)

"""#Calculations

##Rolling Volatility
"""

returns = OPEN_stock_history['Close'].pct_change()
OPEN_stock_history['Rolling Volatility'] = ta.stdev(returns, length=14)
OPEN_stock_history['Rolling Volatility']
OPEN_stock_history['Rolling Volatility'].dropna()

"""##Simple Moving Average"""

OPEN_stock_history['SMA_14'] = ta.sma(OPEN_stock_history['Close'], length=14)
OPEN_stock_history['SMA_14']
OPEN_stock_history['SMA_14'].dropna()

"""##Exponentional Strength Index

"""

OPEN_stock_history['EMA_14'] = ta.ema(OPEN_stock_history['Close'], length = 14)
OPEN_stock_history['EMA_14']
OPEN_stock_history['EMA_14'].dropna()

"""##Relative Strength Index"""

OPEN_stock_history['RSI'] = ta.rsi(OPEN_stock_history['Close'])
OPEN_stock_history['RSI']
OPEN_stock_history['RSI'].dropna()

OPEN_stock_history['Target Close'] = OPEN_stock_history['Close'].shift(-1)

"""#Table of Calculations"""

OPEN_stock_history = OPEN_stock_history.dropna()

"""#Splitting"""

y = OPEN_stock_history['Target Close']
y

X = OPEN_stock_history.drop(['Close', 'Target Close'], axis = 1)
X

OPEN_stock_history = OPEN_stock_history.sort_index()
split_index = int(len(OPEN_stock_history)*0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

"""#Linear Regression"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

y_learn_train_pred = lr.predict(X_train)
y_learn_test_pred = lr.predict(X_test)

y_learn_train_pred

y_learn_test_pred

"""#Error Identification"""

from sklearn.metrics import mean_squared_error, r2_score
lr_train_mse = mean_squared_error(y_train, y_learn_train_pred)
lr_test_mse = mean_squared_error(y_test, y_learn_test_pred)

lr_train_r2 = r2_score(y_train, y_learn_train_pred)
lr_test_r2 = r2_score(y_test, y_learn_test_pred)

print('lr_train_mse =',lr_train_mse, 'lr_train_r2 =',lr_train_r2, 'lr_test_mse =', lr_test_mse, 'lr_test_r2 =',lr_test_r2)

lr_data = pd.DataFrame([
    ['Linear Regressions',lr_train_mse,lr_train_r2,lr_test_mse,lr_test_r2]
    ],
             columns = ['Method','Training MSE','Training R2','Testing MSE','Testing R2'])
lr_data

"""#Random Forest Regression"""

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(max_depth=2, random_state=100)
rf.fit(X_train, y_train)

rf_train_predict = rf.predict(X_train)
rf_test_predict = rf.predict(X_test)

rf_train_predict

rf_test_predict

"""##Random Forest Error"""

rf_train_predict_mse = mean_squared_error(y_train, rf_train_predict)
rf_test_predict_mse = mean_squared_error(y_test, rf_test_predict)

rf_train_predict_r2 = r2_score(y_train, rf_train_predict)
rf_test_predict_r2 = r2_score(y_test, rf_test_predict)

rf_data = pd.DataFrame([['Random Forest Regression',rf_train_predict_mse, rf_test_predict_mse, rf_train_predict_r2, rf_test_predict_r2]],
             columns = ['Method', 'Training MSE', 'Training R2', 'Testing MSE', 'Testing R2'])
rf_data

"""#Regression Comparison"""

OPEN_regression_comparison = pd.concat([lr_data, rf_data], axis =0)

OPEN_regression_comparison

OPEN_regression_comparison.reset_index(drop=True, inplace=True)
OPEN_regression_comparison

"""#Linear Regression Display"""

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(6,6))
plt.scatter(x=y_test, y=y_learn_test_pred)


plt.xlabel('Training')
plt.ylabel('Predicted')
plt.title('Linear Regression Model')

z = np.polyfit(y_test, y_learn_test_pred, 1)
p = np.poly1d(z)

plt.plot(y_test, p(y_test), c="#9CAE00")

latest_price = X.tail(1)
next_day_lr = round(lr.predict(latest_price)[0],2)
next_day_rf= round(rf.predict(latest_price)[0],2)

print("Next Day Predicted Close (Linear Regression): $",next_day_lr)
print("Next Day Predicted Close (Regression Forest): $",next_day_rf)