# -*- coding: utf-8 -*-
"""OPEN Stock Linear Regression Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z18dmB08c0XMMHebaxfloO8zdnTc6i9L

# Install Packages
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import pandas_ta as ta
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import numpy as np

st.title("Stock Prediction Linear Regression Model")

# ------------------ 1. User Inputs ------------------
ticker_symbol = st.text_input("Enter stock ticker:", value="OPEN")
start_date = st.date_input("Start Date", pd.to_datetime("2025-07-01"))
end_date = st.date_input("End Date", pd.to_datetime("2025-12-18"))

# ------------------ 2. Fetch stock data ------------------
@st.cache_data
def get_stock_data(ticker, start, end):
    stock = yf.Ticker(ticker)
    df = stock.history(start=start, end=end)
    return df

df = get_stock_data(ticker_symbol, start_date, end_date)

if df.empty:
    st.error("No data fetched. Check ticker or dates.")
    st.stop()

st.subheader("Stock Data")
st.dataframe(df.tail())

# ------------------ 3. Compute technical indicators ------------------
df['Rolling Volatility'] = ta.stdev(df['Close'].pct_change(), length=14)
df['SMA_14'] = ta.sma(df['Close'], length=14)
df['EMA_14'] = ta.ema(df['Close'], length=14)
df['RSI'] = ta.rsi(df['Close'])

# ------------------ 4. Create next-day target ------------------
df['Target Close'] = df['Close'].shift(-1)

# Drop rows with NaN (from indicators or target)
df = df.dropna()

st.subheader("Calculated Features")
st.dataframe(df.tail())

# ------------------ 5. Feature/target split ------------------
X = df.drop(['Close', 'Target Close'], axis=1)
y = df['Target Close']

# ------------------ 6. Time-series train/test split ------------------
df = df.sort_index()
split_index = int(len(df) * 0.8)

X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

# ------------------ 7. Train Linear Regression ------------------
lr = LinearRegression()
lr.fit(X_train, y_train)

y_train_pred_lr = lr.predict(X_train)
y_test_pred_lr = lr.predict(X_test)

# ------------------ 8. Train Random Forest ------------------
rf = RandomForestRegressor(max_depth=2, random_state=100)
rf.fit(X_train, y_train)

y_train_pred_rf = rf.predict(X_train)
y_test_pred_rf = rf.predict(X_test)

# ------------------ 9. Evaluate models ------------------
st.subheader("Model Performance")
perf_df = pd.DataFrame([
    ['Linear Regression',
     round(mean_squared_error(y_train, y_train_pred_lr),4),
     round(r2_score(y_train, y_train_pred_lr),4),
     round(mean_squared_error(y_test, y_test_pred_lr),4),
     round(r2_score(y_test, y_test_pred_lr),4)],
    ['Random Forest',
     round(mean_squared_error(y_train, y_train_pred_rf),4),
     round(r2_score(y_train, y_train_pred_rf),4),
     round(mean_squared_error(y_test, y_test_pred_rf),4),
     round(r2_score(y_test, y_test_pred_rf),4)]
], columns=['Method','Training MSE','Training R2','Testing MSE','Testing R2'])
st.dataframe(perf_df)

# ------------------ 10. Interactive Plot: Linear Regression Actual vs Predicted ------------------
import plotly.express as px

st.subheader("Linear Regression: Actual vs Predicted (Test Set)")

# Create a dataframe for plotting
plot_df = pd.DataFrame({
    "Actual Close": y_test,
    "Predicted Close": y_test_pred_lr
})

fig = px.scatter(
    plot_df,
    x="Actual Close",
    y="Predicted Close",
    labels={"x":"Actual Close", "y":"Predicted Close"},
    title="Linear Regression Test Set",
    hover_data={"Actual Close":":.2f", "Predicted Close":":.2f"}
)

# Add a regression line
z = np.polyfit(y_test, y_test_pred_lr, 1)
p = np.poly1d(z)
plot_df['Regression Line'] = p(plot_df["Actual Close"])
fig.add_traces(px.line(plot_df, x="Actual Close", y="Regression Line").data)

st.plotly_chart(fig, use_container_width=True)

# ------------------ 11. Next-Day Prediction ------------------
st.subheader("Next-Day Predicted Close")
latest_features = X.tail(1)
next_day_lr = round(float(lr.predict(latest_features)[0]),2)
next_day_rf = round(float(rf.predict(latest_features)[0]),2)

st.write(f"Linear Regression predicted next-day close: **${next_day_lr}**")
st.write(f"Random Forest predicted next-day close: **${next_day_rf}**")
